[package]
name = "ginko_server"
version = "0.0.8"
edition = "2021"
license = "MIT"
description = "A language server library for device-trees"
repository = "https://github.com/Schottkyc137/ginko"
authors = ["Lukas Scheller <lukasscheller@icloud.com>"]
readme = "../README.md"
keywords = ["dts", "device-tree", "language-server", "lsp"]
categories = ["development-tools"]

[dependencies]
itertools = "0.13.0"
parking_lot = "0.12.3"
tower-lsp = "0.20.0"
ginko = { version = "^0.0.8", path = "../ginko" }
url = "2.5.2"
serde = "1"
serde_json = "1"
